// Prepares what the video scenes need that is not committed here:
//   1. Lucide icons the scenes use, written to video/scenes/icons.js (Lucide is ISC licensed).
//   2. Eir brand assets (the rune and the wordmark), copied from a local clone of the Eir design
//      system into video/assets/ (gitignored). The design-system repository carries no licence file,
//      so this repository does not redistribute its logos; each contributor pulls their own copy.
//
//   npm run video:prepare                     assets from ../eir-design-system
//   EIR_DESIGN_SYSTEM=/path npm run video:prepare
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const here = join(root, 'video');

// Icons used by the scenes (Lucide names).
const ICONS = [
  'database',
  'shield-check',
  'git-branch',
  'plug',
  'stethoscope',
  'users',
  'languages',
  'lock',
  'server',
  'file-text',
  'check',
  'x',
  'code',
  'terminal',
  'heart-pulse',
  'globe',
  'brain',
  'workflow',
  'layers',
  'activity',
  'clipboard-check',
  'book-open',
  'git-pull-request',
  'git-fork',
  'flask-conical',
  'zap',
  'arrow-right',
  'circle-check',
  'triangle-alert',
  'key-round',
  'fingerprint',
  'hospital',
  'sparkles',
  'scale',
  'eye',
  'repeat',
  'unlink',
  'package',
  'boxes',
  'replace',
  'hand-heart',
  'user-check',
  'badge-check',
  'search',
  'pill',
  'clipboard-list',
  'file-badge',
  'circle-dashed',
  'lock-keyhole',
  'box',
  'cpu',
  'cloud-off',
];

const nodes: Record<string, unknown> = {};
for (const name of ICONS) {
  const file = join(root, 'node_modules/lucide/dist/esm/icons', `${name}.js`);
  if (!existsSync(file)) throw new Error(`Lucide has no icon ${name}`);
  const [, , children] = (await import(pathToFileURL(file).href)).default;
  nodes[name] = children;
}
writeFileSync(
  join(here, 'scenes/icons.js'),
  `// Generated by video/prepare.ts from Lucide (ISC). Do not edit by hand.\nwindow.ICONS = ${JSON.stringify(nodes)};\n`,
);
console.log(`Wrote ${ICONS.length} icons.`);

const design = resolve(process.env.EIR_DESIGN_SYSTEM ?? join(root, '../eir-design-system'));
const logos = join(design, 'assets/logo');
const out = join(here, 'assets');
mkdirSync(out, { recursive: true });
const copies: [string, string, number][] = [
  ['light-logo-icon.png', 'rune.png', 1200], // white brush rune, transparent
  ['light-logo-v2.png', 'wordmark.png', 1600], // "eir" white + "SPACE" gold, for dark backgrounds
  ['colored-logo-v2.png', 'wordmark-light.png', 1600], // "eir" teal + "SPACE" gold, for light backgrounds
];
if (!existsSync(logos)) {
  console.log(
    `Brand assets not found at ${logos}. Set EIR_DESIGN_SYSTEM to a clone of the Eir design system; scenes fall back to text.`,
  );
} else {
  for (const [from, to, width] of copies) {
    execFileSync('ffmpeg', [
      '-y',
      '-loglevel',
      'error',
      '-i',
      join(logos, from),
      '-vf',
      `scale=${width}:-1:flags=lanczos`,
      join(out, to),
    ]);
    console.log(`Copied ${from} -> video/assets/${to}`);
  }
}
